#!/bin/sh

# Gives a dmenu prompt to open a new LaTeX file or use an existence template.
# You will need zathura and vim to make this work.

# Define default values for variables
: ${VL_DIR:=$HOME/Docs/latex}
: ${VL_TEMPLATE_DIR:=$VL_DIR/templates}
: ${VL_OUTPUT:=/tmp}
: ${VL_COMPILE_METHOD:=pdflatex}

# Create latex forlder if didn't exist.
mkdir -p $VL_TEMPLATE_DIR

# Crete .exrc if didn't exits.
[ -f "$VL_DIR/.exrc" ] || printf "autocmd BufWritePost *.tex !$VL_COMPILE_METHOD
	\\ -jobname='%%:r'
	\\ -output-directory=$VL_OUTPUT
	\\ '%%'
" > "$VL_DIR/.exrc"

err() {
	printf "\033[1;31m%s\033[0m\n" "$*"
	exit 1
}

# Check if necesary files exists
[ -f "$VL_TEMPLATE_DIR/new-article.tex" ] || err "Warning new-article.tex doesn't exists."

# Gives name, date and path to the new document.
docDetails() {
	name=$(printf "%s" | dmenu -p 'Document name:')
	[ -z "$name" ] && exit 1
	path="$VL_DIR/$name.tex"
}

# Open suckless tabbed[vim+zathura].
openGui() {
	# Open window.
	xid="$(tabbed -c -d -s -r 2 st -w x)"

	# Create a new output.pdf and open it with zathura.
	cd "$VL_DIR"
	x="${doc##*/}"
	y="${x%%.tex}"
	$VL_COMPILE_METHOD -jobname="${name:-$y}" -output-directory="$VL_OUTPUT" "$doc"
	zathura "$VL_OUTPUT/${name:-$y}.pdf" -e "$xid" 2>/dev/null &

	# Open nvim.
	if [ ! -z "$path" ]; then
		st -w "$xid" nvim "$path" -c "silent read $doc" 2>/dev/null &
	else
		st -w "$xid" nvim "$doc" 2>/dev/null &
	fi
}

# Return a .tex file in a given folder
getTex() {
	printf "$*/%s" "$(for file in "$*"/*.tex; do
		[ -f "$file" ] || continue
		printf '%s\n' "${file##*/}"
	done | dmenu -p 'Choose template:')"
}

# Options:
OP1="Empty file"
OP2="Choose template"
OP3="Open an existence file"
# Choose an option and check if string is not empty.
option=$(printf "$OP1\n$OP2\n$OP3" | dmenu -p 'Choose an option:')
[ -z "$option" ] && exit 1

if [ "$option" = "$OP1" ]; then
	# Use a simple default template
	doc="$VL_TEMPLATE_DIR/new-article.tex"
	docDetails
	openGui
elif [ "$option" = "$OP2" ]; then
	# Choose a template.
	doc="$(getTex $VL_TEMPLATE_DIR)"
	[ -f "$doc" ] || exit 1
	docDetails
	openGui
elif [ "$option" = "$OP3" ]; then
	# Select and compile a ".tex" file from $VL_DIR
	doc="$(getTex $VL_DIR)"
	[ -f "$doc" ] || exit 1
	openGui
fi
