#!/bin/sh

# TODO:
# 1. Organize and refactorize the variables inside 'docDetails()'
# 2. Avoid using the '$doc' variable in this way '$doc.tex'
# 3. Use 'chTemp()' to select templates and existing files. Get rid of find.
# 4. Create loop to map options 'OP1,OP2,OP3...'

# Gives a dmenu prompt to open a new LaTeX file or use an existence template.
# You will need zathura and vim to make this work.

# Gives name, date and path to the new document.
docDetails() {
	document_name=$(printf "%s" | dmenu -p 'Document name:')
	test -z "$document_name" && exit 1
	date=$(date +%R)
	name_date="$document_name [$date]"
	full_path="$VIM_LATEX_FOLDER/$name_date.tex"
}

# Open suckless tabbed[vim+zathura].
openGui() {
	# Open window.
	xid="$(tabbed -c -d -s -r 2 st -w x)"

	# Create a new output.pdf and open it with zathura.
	cd "$VIM_LATEX_FOLDER"
	pdflatex -jobname="${name_date:-$doc}" -output-directory="$VIM_LATEX_OUTPUT" "$doc.tex"
	zathura "$VIM_LATEX_OUTPUT/${name_date:-$doc}.pdf" -e "$xid" 2>/dev/null &

	# Open vim.
	if [ ! -z "$full_path" ]; then
		st -w "$xid" nvim "$full_path" -c "silent read $doc.tex" 2>/dev/null &
		#alacritty --embed $(printf "%d\n" $xid) -e nvim "$full_path" -c "silent read $doc.tex" 2>/dev/null &
	else
		st -w "$xid" nvim "$doc.tex" 2>/dev/null &
		#alacritty --embed -e nvim "$doc.tex" 2>/dev/null &
	fi
}

# Ask for template name inside $VIM_LATEX_TEMPLATE_DIR
chTemp() {
	ls -1 "$VIM_LATEX_TEMPLATE_DIR" | sed -e 's/\..*$//' | dmenu -p 'Choose template:'
}

# Options:
OP1="Empty file"
OP2="Choose template"
OP3="Open an existence file"
# Choose an option and check if string is not empty.
option=$(printf "$OP1\n$OP2\n$OP3" | dmenu -p 'Choose an option:')
test -z "$option" && exit 1

if [ "$option" = "$OP1" ]; then			# Use default "new article.tex" template.
	doc="$VIM_LATEX_TEMPLATE_DIR/new article"
	docDetails
	openGui  
elif [ "$option" = "$OP2" ]; then		# Choose a template.
	tN=$(chTemp)
	test -z "$tN" && exit 1
	doc="$VIM_LATEX_TEMPLATE_DIR/$tN"
	docDetails
	openGui
elif [ "$option" = "$OP3" ]; then		# Select and compile a ".tex" file from $VIM_LATEX_FOLDER
	doc=$(
		find $VIM_LATEX_FOLDER \
		-maxdepth 1 \
		-iname "*.tex" \
		-execdir basename {} .tex ';' | dmenu -p "Choose document:"
	)
	test -z "$doc" && exit 1
	openGui
fi
